services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env   # ან უბრალოდ - .env, გააჩნია სად გიდევს ფაილი
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - INTERNAL_API_URL=http://backend:8000/api
      - NODE_ENV=production
    command: sh -c "npm run build && npm start"
    depends_on:
      - backend

volumes:
  db_data: