# Generated by Django 6.0.4 on 2026-05-07 09:31

import django.core.validators
import django.db.models.deletion
import exhibits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description_ka', models.CharField(help_text='Short annotation — 1-2 sentences', max_length=300)),
                ('short_description_en', models.CharField(blank=True, max_length=300)),
                ('description_ka', models.TextField()),
                ('description_en', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('jewelry', 'Jewelry'), ('weapon', 'Weapon'), ('pottery', 'Pottery'), ('religious', 'Religious Object'), ('coin', 'Coin'), ('tool', 'Tool'), ('manuscript', 'Manuscript'), ('sculpture', 'Sculpture'), ('textile', 'Textile'), ('other', 'Other')], default='other', max_length=20)),
                ('culture', models.CharField(blank=True, max_length=100)),
                ('date_range', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=150)),
                ('dimensions', models.CharField(blank=True, max_length=150)),
                ('origin_location', models.CharField(blank=True, max_length=200)),
                ('audio_annotation_ka', models.FileField(blank=True, upload_to='artifacts/audio/')),
                ('audio_annotation_en', models.FileField(blank=True, upload_to='artifacts/audio/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name_ka'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_ka', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('era_start_year', models.IntegerField(help_text='Negative number for BCE, e.g. -800')),
                ('era_end_year', models.IntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=exhibits.models.artifact_image_path)),
                ('caption_ka', models.CharField(blank=True, max_length=300)),
                ('caption_en', models.CharField(blank=True, max_length=300)),
                ('image_type', models.CharField(choices=[('hero', 'Hero'), ('detail', 'Detail'), ('reconstruction', 'Reconstruction'), ('context', 'Context')], default='detail', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibits.artifact')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='exhibits.period'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description_ka', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('panorama_360', models.ImageField(blank=True, help_text='360° panoramic image (equirectangular format)', upload_to=exhibits.models.room_panorama_path)),
                ('audio_guide_ka', models.FileField(blank=True, upload_to=exhibits.models.room_audio_path)),
                ('audio_guide_en', models.FileField(blank=True, upload_to=exhibits.models.room_audio_path)),
                ('cover_image', models.ImageField(blank=True, upload_to='rooms/covers/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='exhibits.period')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='exhibits.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='exhibits.room'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='artifacts', to='exhibits.topic'),
        ),
        migrations.CreateModel(
            name='ArtifactTurntableFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=exhibits.models.artifact_turntable_path, validators=[django.core.validators.MaxValueValidator(359)])),
                ('angle', models.PositiveSmallIntegerField(help_text='Angle in degrees, 0-359')),
                ('order', models.PositiveSmallIntegerField(help_text='Frame order, starting from 0')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turntable_frames', to='exhibits.artifact')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('artifact', 'order')},
            },
        ),
    ]
