# Generated by Django 6.0.4 on 2026-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='met_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
