# Generated by Django 6.0.4 on 2026-05-14 07:19

import django.core.validators
import exhibits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0002_artifact_met_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactturntableframe',
            name='angle',
            field=models.PositiveSmallIntegerField(help_text='Angle in degrees, 0-359', validators=[django.core.validators.MaxValueValidator(359)]),
        ),
        migrations.AlterField(
            model_name='artifactturntableframe',
            name='image',
            field=models.ImageField(upload_to=exhibits.models.artifact_turntable_path),
        ),
    ]
