# Generated by Django 6.0.4 on 2026-05-15 15:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibits', '0003_alter_artifactturntableframe_angle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='_slug_source', unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='_slug_source', unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='_slug_source', unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='_slug_source', unique=True),
        ),
    ]
